server:
  port: 8090
spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/demo12345
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: productapp