spring:
  config:
    import: optional:configserver:http://localhost:8071
  profiles:
    active:
      - "qa"
  jpa:
    show-sql: true
  application:
    name: coupons
server:
  port: 8089
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    info:
      enabled: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/
build:
  version: "1.0"
info:
  message: "Welcome to busycoder coupon default profile"
  name: "Raj: Product Owner coupon default profile"