spring:
  config:
    import: configserver:http://localhost:8071
  profiles:
    active:
      - "qa"
  jpa:
    show-sql: true
  application:
    name: customers
server:
  port: 8081
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    info:
      enabled: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

build:
  version: "1.0"
info:
  message: "Welcome to busycoder customer default profile"
  name: "Raj: Product Owner customer default profile"

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
